const appointmentSetting = (description) => ({
  title: "B2B Appointment Setting",
  description,
  href: "https://www.callteam.ca/services/b2b-appointment-setting/",
});

const outsourcedSdr = (description) => ({
  title: "Outsourced SDR Services",
  description,
  href: "https://www.callteam.ca/services/outsourced-sdr/",
});

const aiGtm = (description) => ({
  title: "AI GTM Services",
  description,
  href: "https://www.callteam.ca/services/ai-gtm/",
});

const completeScript = (opening, questions, bridge, cta) => `${opening}

If relevant:
${questions.map((question) => `• ${question}`).join("\n")}

Bridge: ${bridge}

CTA: ${cta}`;

const resources = [
  {
    id: "CT-R046",
    slug: "marketing-automation-consulting-cold-call-script",
    title: "Marketing Automation Consulting Cold Call Script",
    seoTitle: "Marketing Automation Consulting Cold Call Script",
    metaDescription: "Use this free marketing automation cold call script to uncover CRM, lead routing and follow-up gaps and book a focused workflow review.",
    publishedDate: "2026-08-23",
    category: "Marketing Automation Consulting",
    industry: "Marketing technology, CRM consulting, lifecycle marketing and revenue operations",
    subindustry: "Marketing automation setup, cleanup, migration, lead routing and campaign operations",
    serviceCategory: "Marketing automation consulting and workflow assessment",
    icp: "B2B companies with a CRM or marketing automation platform that still rely on manual lead handling, disconnected campaigns or unreliable reporting.",
    companySize: "Growth-stage companies through global enterprises",
    geography: "Global",
    buyers: ["Chief Marketing Officer", "VP Marketing", "Marketing Operations Director", "Demand Generation Director", "CRM Director", "Revenue Operations Director"],
    buyerLevel: "Marketing, revenue operations and CRM leader",
    objective: "Book a focused marketing automation workflow review",
    scenario: "The buyer already has tools and does not want a broad technology pitch. The opening needs to find one practical gap that is costing the team time or follow-up.",
    triggers: ["CRM migration", "New marketing leader", "Campaign growth", "Lead routing changes", "Marketing operations hiring", "Reporting gaps", "New market launch"],
    archetype: "Problem-led marketing workflow review",
    primaryKeyword: "marketing automation cold call script",
    secondaryKeywords: ["marketing automation consulting sales script", "CRM consulting cold call script", "marketing operations prospecting script", "martech cold call script"],
    filters: ["Technology", "Executive"],
    copyLabel: "Copy this script",
    opening: "Hi [First Name], [Your Name] with [Company]. Quick question. Are leads and customer follow-ups moving through your CRM the way you want, or is your team still fixing gaps by hand?",
    questions: [
      "Where are good leads most likely to get stuck, delayed or missed?",
      "What does the team still update, move or chase manually?",
      "Is the bigger issue routing, follow-up, reporting or campaign setup?",
      "Who owns fixing that workflow when it stops working?",
    ],
    bridge: "We help marketing teams fix one automation problem at a time. We map what happens now, find the handoff that is breaking and show what a cleaner setup could look like without turning the first call into a platform overhaul.",
    cta: "Would a 15-minute workflow review next week be useful to see if that one gap is worth fixing?",
    objections: [
      { objection: "We already have an automation platform.", response: "That makes sense. We usually speak with teams that already have one. The question is whether the current setup is doing the job without extra manual work." },
      { objection: "Our internal team handles this.", response: "Understood. We can simply look at one workflow they want to improve or do not have time to rebuild. If there is no gap, there is no reason to continue." },
      { objection: "Send me information.", response: "Happy to. Should I make it about lead routing, follow-up, reporting or campaign operations so it is actually useful?" },
      { objection: "This is not a priority.", response: "No problem. Is there a CRM change, campaign launch or planning period when it would make more sense to revisit it?" },
    ],
    whyItWorks: "The call does not sell a complicated transformation. It asks whether one visible marketing workflow is working, lets the buyer name the gap and offers a small review with a clear purpose.",
    whyBreakdown: [
      { label: "It starts with daily work", text: "The buyer can answer from experience without decoding marketing technology language." },
      { label: "It respects the current stack", text: "The caller assumes tools are already in place and looks for a setup or process gap." },
      { label: "It keeps the scope small", text: "One broken handoff is easier to discuss than a full CRM or automation program." },
      { label: "It earns the meeting", text: "The review has a defined workflow, owner and reason instead of a generic capabilities presentation." },
    ],
    personalization: [
      "Choose one workflow the consultant can genuinely improve, such as routing, nurture, lifecycle stages, scoring or reporting.",
      "Use a public CRM change, marketing hire, product launch or campaign expansion only as a reason to ask a question.",
      "For a CMO, talk about missed follow-up and visibility. For Marketing Operations, talk about the exact handoff and manual work.",
      "Do not claim revenue impact, attribution accuracy or implementation speed without the buyer's baseline and approved evidence.",
    ],
    alternatives: [
      { label: "Short version", description: "Use when the buyer wants the point immediately.", script: "Hi [First Name], [Your Name] with [Company]. Is there one lead or customer workflow your team is still holding together manually even though you have automation tools?" },
      { label: "Voicemail", description: "Leave one clear marketing operations reason to respond.", script: "Hi [First Name], this is [Your Name] with [Company]. I am calling about lead routing and follow-up gaps inside existing marketing systems. I will send a short note. My number is [Phone Number]." },
      { label: "Marketing Operations opener", description: "Use with the person closest to the workflow.", script: "Hi [First Name], [Your Name] with [Company]. Which part of your lead flow creates the most cleanup today: capture, routing, nurture, handoff or reporting?" },
    ],
    signalRadar: {
      heading: "Find teams with a live marketing workflow problem",
      summary: "The CallTeam Buyer Signal Radar looks for changes that can put pressure on lead handling, campaign operations or CRM ownership. It helps callers choose a timely question without pretending a signal proves the company wants consulting.",
      signals: [
        { label: "Platform change", text: "A CRM migration, new marketing platform or integration project can create setup and ownership work." },
        { label: "Leadership change", text: "A new marketing or revenue operations leader may be reviewing how leads move through the funnel." },
        { label: "Campaign growth", text: "New products, markets and channels can expose routing, nurture and reporting gaps." },
        { label: "Operations hiring", text: "Repeated CRM and marketing operations roles can point to workload or capability pressure." },
      ],
      activation: "CallTeam AI GTM turns the selected signal into a short account brief, likely buyer map and one approved problem hypothesis. A human caller asks the simple question, listens for a real gap and books a review only when the buyer sees value in it.",
    },
    campaignPlan: {
      listFocus: "B2B organizations with an established CRM or automation platform, meaningful campaign volume and a clear marketing or revenue operations owner.",
      callAround: "One observable change such as a CRM project, new marketing leader, campaign expansion, product launch or marketing operations hiring pattern.",
      meetingReady: "The buyer identifies a workflow, explains where it breaks or creates manual work and agrees that a focused review could help.",
      handoff: "Record the current tools, problem workflow, manual steps, affected teams, owner, timing and the single question the review should answer.",
    },
    faqs: [
      { question: "What is a good marketing automation cold call opener?", answer: "Ask whether one lead or customer workflow is moving through the current system cleanly or still needs manual correction. That is easier to answer than a broad question about digital transformation." },
      { question: "Who should a marketing automation consulting call target?", answer: "Start with Marketing Operations, CRM, Demand Generation or Revenue Operations. A CMO or VP Marketing may sponsor the work, while technical stakeholders may join when integrations or data are involved." },
      { question: "How do you cold call a company that already has marketing automation software?", answer: "Do not pitch another platform by default. Ask where the existing setup leaves a routing, follow-up, reporting or ownership gap that the team wants to improve." },
      { question: "What makes a marketing automation meeting qualified?", answer: "The buyer can name the workflow, current tools, manual work, business effect, internal owner and purpose of the review. A platform name alone is not enough." },
      { question: "How is this different from the paid media agency script?", answer: "This page owns CRM, lifecycle and workflow automation consulting intent. The paid media script focuses on advertising execution, campaign economics and media performance." },
    ],
    aboutCallTeam: {
      heading: "About CallTeam, global marketing technology lead generation and appointment setting",
      paragraphs: [
        "CallTeam is a global B2B lead generation, human cold-calling and appointment-booking company for technology providers, consultants and complex service firms. We research target accounts, identify the right buying roles, build a clear reason for the call, speak with prospects and book qualified meetings straight into the client's calendar. For marketing automation consulting, that means we do not treat every company with a CRM as an opportunity. Our callers look for a real workflow question, confirm who owns it and document why a review would be useful before asking the consultant to spend time on a meeting.",
        "Our team supports outbound campaigns across SaaS, AI, cybersecurity, healthcare, financial services, manufacturing, logistics, workforce technology, marketing services and professional services in global markets. Marketing technology sales often becomes too technical too early, so CallTeam keeps the first conversation grounded in missed follow-up, manual work, weak visibility and unclear ownership. We can reach CMOs, Marketing Operations leaders, Demand Generation teams, CRM owners and Revenue Operations buyers while respecting the tools and internal specialists already in place. Claims about revenue, attribution, savings or implementation remain inside evidence the provider can support.",
        "CallTeam AI GTM and the proprietary CallTeam Buyer Signal Radar organize public business changes, account fit, buyer roles and approved campaign evidence before outreach begins. The technology helps the team prepare; experienced human callers remain responsible for the conversation, objection handling, qualification and meeting decision. CallTeam is also building a public resource centre designed to exceed 100 original cold-call scripts, buyer playbooks, objection guides and practical B2B sales articles for founders, SDRs, revenue teams and buyers. That growing library explains how our global B2B appointment setting and marketing technology lead generation work is actually carried out.",
      ],
      points: ["CMO and marketing operations account research", "CRM and workflow signal prioritization", "Simple human cold calling", "Qualified workflow-review booking and handoff"],
    },
    related: ["digital-marketing-agency-cold-call-script-paid-media", "b2b-saas-cold-call-script", "event-marketing-software-cold-call-script"],
    relevantServices: [appointmentSetting("Book marketing workflow reviews with a defined problem and responsible buyer."), outsourcedSdr("Add account research, human calling, qualification and clear campaign handoff."), aiGtm("Prioritize companies showing relevant CRM, leadership, campaign and operations signals.")],
  },
  {
    id: "CT-R047",
    slug: "business-intelligence-software-cold-call-script",
    title: "Business Intelligence Software Cold Call Script",
    seoTitle: "Business Intelligence Software Cold Call Script",
    metaDescription: "Use this free business intelligence cold call script to uncover reporting delays, qualify an analytics use case and book a focused BI software demo.",
    publishedDate: "2026-08-23",
    category: "Business Intelligence Software",
    industry: "Business intelligence, analytics software, data platforms and executive reporting",
    subindustry: "Operational dashboards, finance reporting, self-service analytics and data visibility",
    serviceCategory: "Business intelligence software demo appointment setting",
    icp: "Organizations with recurring reporting delays, disconnected data or decision-makers who struggle to get a reliable answer without analyst support.",
    companySize: "Mid-market organizations through global enterprises",
    geography: "Global",
    buyers: ["Chief Financial Officer", "Chief Information Officer", "Chief Data Officer", "VP Analytics", "Business Intelligence Director", "Finance Transformation Director", "Operations Director"],
    buyerLevel: "Finance, data, technology and operations decision-maker",
    objective: "Book a qualified BI software discovery call or focused demo",
    scenario: "The buyer may already have dashboards, analysts and reporting tools. The call needs to find one decision that is still slow, unclear or hard to trust.",
    triggers: ["Board reporting pressure", "Data platform project", "ERP change", "Acquisition", "Analytics hiring", "Reporting backlog", "New CFO or data leader"],
    archetype: "Decision-led reporting discovery",
    primaryKeyword: "business intelligence cold call script",
    secondaryKeywords: ["BI software sales script", "analytics software cold call script", "business intelligence prospecting script", "BI demo booking script"],
    filters: ["Technology", "Finance", "Executive"],
    copyLabel: "Copy this script",
    opening: "Hi [First Name], [Your Name] with [Company]. I will keep this simple. When you need a clear answer from company data, does your team get it quickly, or are people still waiting on reports and checking different numbers?",
    questions: [
      "Which report or decision creates the most back-and-forth today?",
      "Where does the information come from now?",
      "Is the problem speed, trust, access or too much manual work?",
      "Who needs to agree before a new reporting approach is considered?",
    ],
    bridge: "We help teams look at one reporting use case before showing them a full BI platform. The first session uses the buyer's real question, current sources and users so the demo stays useful and does not become a tour of every dashboard feature.",
    cta: "Would it make sense to spend 15 minutes on that one reporting problem and see if a focused demo is worth booking?",
    objections: [
      { objection: "We already have BI tools.", response: "Most teams we call do. Is there one report or decision the current setup still makes harder than it should be?" },
      { objection: "Our data team builds the reports.", response: "That may be working well. I am only asking whether they have a backlog or a use case where business users still wait too long for an answer." },
      { objection: "Our data is not ready.", response: "That is useful to know. A short conversation could define whether the next step is better data work, not more software." },
      { objection: "Send a demo video.", response: "I can. Which use case should it show so you do not get a generic dashboard video that misses the point?" },
    ],
    whyItWorks: "This BI cold call begins with a decision the buyer needs to make, not a lecture about data architecture. It discovers one reporting problem and protects the demo from becoming a feature dump.",
    whyBreakdown: [
      { label: "It uses a familiar frustration", text: "Waiting for a report or reconciling numbers is easy for buyers to recognize." },
      { label: "It avoids tool replacement language", text: "The current BI stack may stay in place while one use case is examined." },
      { label: "It finds the real constraint", text: "Speed, trust, access and manual work lead to different next steps." },
      { label: "It gives the demo a job", text: "The meeting is organized around one decision, data source and group of users." },
    ],
    personalization: [
      "Choose one reporting or decision use case that fits the buyer, such as board reporting, forecasting, operations, margin or customer performance.",
      "Use an ERP change, acquisition, data hire or executive appointment as context, never as proof that reporting is broken.",
      "Ask CFOs about decisions and confidence. Ask data leaders about access, backlog and governance. Ask operations about action and timing.",
      "Avoid claims about real-time data, accuracy, integration or return unless the product and customer environment can support them.",
    ],
    alternatives: [
      { label: "Short version", description: "Use with a busy executive.", script: "Hi [First Name], [Your Name] with [Company]. What is one business question your team still cannot answer quickly without pulling reports together by hand?" },
      { label: "Voicemail", description: "Leave a decision-led BI message.", script: "Hi [First Name], this is [Your Name] with [Company]. I am reaching out about a reporting use case where leaders may still wait for a clear answer. I will send the context. My number is [Phone Number]." },
      { label: "CFO opener", description: "Use when finance owns the need.", script: "Hi [First Name], [Your Name] with [Company]. Which number takes the most work to trust at month end or before a major decision?" },
    ],
    signalRadar: {
      heading: "Find organizations with a reason to improve reporting",
      summary: "The CallTeam Buyer Signal Radar looks for events that can increase reporting pressure or create new data questions. The signal guides research, but the buyer still decides whether there is a problem worth discussing.",
      signals: [
        { label: "Executive reporting", text: "A new CFO, board requirement or planning cycle can change which answers leaders need and how quickly they need them." },
        { label: "System change", text: "ERP, warehouse, CRM and data-platform projects can create a window to revisit reporting workflows." },
        { label: "Business complexity", text: "Acquisitions, new business units and geographic growth can introduce more sources and definitions." },
        { label: "Analytics capacity", text: "BI hiring, reporting backlogs and transformation roles may point to rising demand on the data team." },
      ],
      activation: "CallTeam AI GTM combines the relevant signal with the likely reporting use case, account profile and buyer map. Human callers keep the language plain, verify the actual problem and book a demo only when the prospect can name the answer they need.",
    },
    campaignPlan: {
      listFocus: "Organizations with enough operational or financial complexity to support a defined analytics use case and an identifiable data, finance or business owner.",
      callAround: "One reporting pressure such as a system change, acquisition, executive appointment, planning cycle, data project or visible analytics hiring pattern.",
      meetingReady: "The prospect names a report or decision, current sources, user group, main frustration and reason a new approach deserves review.",
      handoff: "Capture the business question, current process, data sources, users, trust or timing issue, existing tools, stakeholders and desired demo outcome.",
    },
    faqs: [
      { question: "What is a strong business intelligence cold call opener?", answer: "Ask about one decision or report that still takes too long or causes people to compare different numbers. Keep the first question understandable to a business leader." },
      { question: "Who should a BI software sales call target?", answer: "CFOs, CIOs, data leaders and BI teams often share the decision. The best first contact is usually the person accountable for the reporting use case, not simply the person who administers a tool." },
      { question: "How do you sell BI software when the prospect already has dashboards?", answer: "Look for a specific gap in speed, trust, access, adoption or manual work. Do not assume the existing platform must be removed." },
      { question: "What qualifies a business intelligence demo?", answer: "A qualified demo has a clear question, current data sources, users, pain point, buyer group and purpose. A general interest in analytics is too broad." },
      { question: "How is this different from the ERP modernization script?", answer: "This page owns analytics, reporting and decision-visibility intent. The ERP modernization script focuses on the core transaction system, operating model and finance transformation decision." },
    ],
    aboutCallTeam: {
      heading: "About CallTeam, global BI software lead generation and demo appointment setting",
      paragraphs: [
        "CallTeam is a global B2B lead generation, human cold-calling and appointment-setting company for software vendors, technology providers and complex B2B services. We research accounts, map decision-makers, develop the campaign language, make live calls, qualify the opportunity and book meetings straight into the client's calendar with useful notes. In a business intelligence campaign, a company is not qualified simply because it stores a lot of data. CallTeam callers identify the business question, current reporting process, people affected and reason to review a new approach before a software specialist runs a demonstration.",
        "Our global campaign experience includes enterprise software, AI, cybersecurity, healthcare, financial services, manufacturing, logistics, workforce platforms, data services and professional services. BI opportunities can involve CFOs, CIOs, data leaders, analytics teams, finance transformation and operations. CallTeam keeps the opening easy to understand, then helps map the buying committee and the evidence each person may need. We do not invent reporting problems or promise perfect data, instant integration, real-time performance or financial returns. The buyer's current environment and the vendor's approved capabilities define what can be discussed credibly.",
        "CallTeam AI GTM and the owned CallTeam Buyer Signal Radar bring structure to account selection before a number is dialed. They organize signals such as system changes, acquisitions, executive appointments, reporting pressure and analytics hiring, then connect them to a likely use case and buyer group for human review. Experienced callers test the idea in conversation and remain accountable for qualification. CallTeam's growing public resource centre is designed to exceed 100 original cold-call scripts, industry playbooks, objection guides and educational articles for founders, B2B buyers, SDRs and revenue leaders. It documents the practical method behind our global appointment booking and analytics software lead generation work.",
      ],
      points: ["Finance, data and operations buyer mapping", "Reporting and system-change signal research", "Plain-English human cold calling", "Use-case qualification and demo booking"],
    },
    related: ["erp-modernization-cold-call-script-for-cfos", "private-credit-software-cold-call-script", "b2b-saas-cold-call-script"],
    relevantServices: [appointmentSetting("Book BI discovery calls around one decision and reporting use case."), outsourcedSdr("Add account research, live calls, qualification and context-rich demo handoff."), aiGtm("Prioritize accounts showing relevant reporting, system, leadership and data signals.")],
  },
  {
    id: "CT-R048",
    slug: "hris-implementation-services-cold-call-script",
    title: "HRIS Implementation Services Cold Call Script",
    seoTitle: "HRIS Implementation Services Cold Call Script",
    metaDescription: "Use this free HRIS cold call script to find rollout, adoption and workflow gaps and book a focused implementation services discovery call.",
    publishedDate: "2026-08-23",
    category: "HRIS Implementation Services",
    industry: "Human resources technology, HR operations, workforce systems and transformation services",
    subindustry: "HRIS implementation, rollout, optimization, adoption, migration and post-launch support",
    serviceCategory: "HRIS implementation and optimization consulting",
    icp: "Organizations buying, rolling out or improving an HR information system across teams, locations or acquired businesses.",
    companySize: "Mid-market employers through global enterprises",
    geography: "Global",
    buyers: ["Chief Human Resources Officer", "VP People", "HRIS Director", "HR Operations Director", "Chief Information Officer", "Transformation Director"],
    buyerLevel: "HR, people operations, technology and transformation leader",
    objective: "Book a qualified HRIS implementation or optimization discovery call",
    scenario: "The buyer may already have a software vendor and implementation partner. The call needs to uncover one unfinished rollout, adoption or process issue without attacking either one.",
    triggers: ["HRIS purchase", "Implementation delay", "Merger or acquisition", "Global expansion", "HR transformation hire", "Adoption issue", "New CHRO or HRIS leader"],
    archetype: "Rollout-stage HRIS discovery",
    primaryKeyword: "HRIS cold call script",
    secondaryKeywords: ["HRIS implementation sales script", "HR technology consulting cold call script", "HRIS services prospecting script", "HRIS implementation appointment setting"],
    filters: ["Technology", "Operations", "Executive"],
    copyLabel: "Copy this script",
    opening: "Hi [First Name], [Your Name] with [Company]. I am calling with one quick question. Is your HR system rollout doing what the team expected, or are there still parts of the process people work around?",
    questions: [
      "Which part of the rollout is taking the most effort now?",
      "Are the biggest gaps in setup, data, adoption or day-to-day process?",
      "Which teams or locations are feeling it most?",
      "Who owns getting the remaining work finished?",
    ],
    bridge: "We help HR and IT teams finish the parts of an HRIS rollout that are still slowing people down. We start with one process or user group, understand what is already in place and decide whether extra implementation help is even needed.",
    cta: "Would a 15-minute implementation check around that one area be useful next week?",
    objections: [
      { objection: "Our software vendor is handling it.", response: "That may be exactly right. We are not calling to replace them. Is there any internal process, adoption or cleanup work that still sits with your team?" },
      { objection: "The implementation is complete.", response: "Good to hear. Are people using the system as planned, or is there one process they still handle outside it?" },
      { objection: "We do not have budget.", response: "Understood. Then the useful question is whether the issue should stay on the internal plan. There is no point in booking a meeting without a real need or path." },
      { objection: "Send me information.", response: "Of course. Should I send something on rollout support, adoption, data, process design or post-launch cleanup?" },
    ],
    whyItWorks: "The script sounds like a practical check-in, not an HR technology lecture. It respects the system and existing partners, then looks for one unfinished piece that may justify outside help.",
    whyBreakdown: [
      { label: "It starts after the purchase", text: "Many service opportunities appear during rollout, adoption and cleanup rather than software selection." },
      { label: "It avoids blame", text: "The current vendor, internal team and original decision do not need to be criticized." },
      { label: "It narrows the work", text: "One process, location or user group creates a manageable first conversation." },
      { label: "It identifies ownership", text: "The call finds who is accountable for closing the gap before a meeting is booked." },
    ],
    personalization: [
      "Choose the relevant stage: planning, migration, configuration, rollout, adoption, optimization or post-launch support.",
      "Use a new HRIS, merger, expansion, implementation role or HR transformation program as context without claiming the project is in trouble.",
      "Ask HR leaders about employee and process impact. Ask HRIS and IT leaders about delivery, ownership and support boundaries.",
      "Do not promise a launch date, data quality, adoption result or system capability before discovery confirms the scope.",
    ],
    alternatives: [
      { label: "Short version", description: "Use when the buyer has little time.", script: "Hi [First Name], [Your Name] with [Company]. Is there one part of your HRIS rollout that still needs more manual work than the team expected?" },
      { label: "Voicemail", description: "Leave a simple rollout-support message.", script: "Hi [First Name], this is [Your Name] with [Company]. I am calling about HRIS rollout and post-launch support where teams still have setup, data, adoption or process work. I will send a note. My number is [Phone Number]." },
      { label: "HRIS Director opener", description: "Use with the operational system owner.", script: "Hi [First Name], [Your Name] with [Company]. Which part of the HRIS plan is still taking the most team time after the main rollout?" },
    ],
    signalRadar: {
      heading: "Find organizations inside an HRIS change window",
      summary: "The CallTeam Buyer Signal Radar looks for observable events that can create implementation or adoption work. It helps the campaign time a relevant question while leaving the buyer free to say the project is on track.",
      signals: [
        { label: "System rollout", text: "A new HRIS, migration or implementation role can indicate an active delivery period." },
        { label: "Workforce change", text: "Expansion, restructuring and acquisitions can add locations, policies, data and user groups." },
        { label: "Leadership movement", text: "A new CHRO, HRIS leader or transformation executive may review delivery and adoption priorities." },
        { label: "Post-launch pressure", text: "Support hiring, process projects and repeated change roles may point to remaining internal work." },
      ],
      activation: "CallTeam AI GTM connects the change event to a likely rollout stage, target role and approved service scope. A human caller asks what is actually unfinished, respects the existing team and books a meeting only when added help could solve a defined problem.",
    },
    campaignPlan: {
      listFocus: "Organizations with a visible HR technology change, enough workforce complexity to require implementation support and clear HR or IT ownership.",
      callAround: "One credible event such as an HRIS purchase, implementation hire, acquisition, expansion, new HR leader or public transformation program.",
      meetingReady: "The prospect identifies the rollout stage, unfinished process, affected users, internal owner and reason outside implementation help may be useful.",
      handoff: "Record the system, stage, scope, process gap, users or locations affected, current partners, internal owner, timing and purpose of the next call.",
    },
    faqs: [
      { question: "What is a good HRIS implementation services cold call opener?", answer: "Ask whether the rollout is working as expected or whether one process still requires a workaround. The question should be understandable without technical implementation language." },
      { question: "Who should an HRIS services call target?", answer: "HRIS Directors and HR Operations leaders often own delivery, while CHROs, IT and transformation leaders may sponsor the work or control resources." },
      { question: "How do you sell HRIS support when the buyer has an implementation partner?", answer: "Respect the partner and ask whether internal process, data, adoption, testing or post-launch work remains outside their scope. Do not manufacture conflict." },
      { question: "What makes an HRIS implementation meeting qualified?", answer: "The buyer can name the system, rollout stage, unfinished work, affected users, owner, timing and reason additional help may be considered." },
      { question: "How is this different from the AI recruiting software script?", answer: "This page owns HRIS rollout, adoption and implementation services. The AI recruiting page focuses on a specific talent acquisition product, workflow and governance decision." },
    ],
    aboutCallTeam: {
      heading: "About CallTeam, global HR technology lead generation and appointment setting",
      paragraphs: [
        "CallTeam is a global B2B lead generation, human cold-calling and appointment-booking company serving technology vendors, consultants and complex service providers. We build the target account list, identify buying roles, prepare the campaign message, make live calls, qualify interest and book meetings straight into the client's calendar with the operating context included. For HRIS implementation services, we focus on the actual stage of change and the work still owned by the buyer. A software purchase, job posting or transformation program is only a reason to research the account, not proof that the organization needs outside support.",
        "Our team works across SaaS, AI, cybersecurity, healthcare, financial services, manufacturing, logistics, workforce software, professional services and other global B2B markets. HR technology campaigns can involve CHROs, People leaders, HR Operations, HRIS, IT, Finance and transformation teams. CallTeam keeps the phone conversation simple while qualifying system stage, process gaps, user adoption, data work, locations, ownership and existing partners. We respect internal delivery teams and do not make unsupported statements about compliance, launch dates, adoption, integrations or return. The next meeting must have a practical reason that the buyer understands.",
        "CallTeam AI GTM and the proprietary CallTeam Buyer Signal Radar help our researchers organize HR system changes, leadership moves, acquisitions, workforce growth and implementation hiring before outreach begins. The tools improve preparation, while experienced callers remain accountable for the language, objection response, qualification and final meeting decision. CallTeam is also developing a public resource centre intended to exceed 100 original cold-call scripts, buyer playbooks, objection guides and B2B sales articles for founders, buyers, revenue leaders and working callers. This growing body of useful content shows search engines and AI answer platforms how CallTeam carries out global HR technology lead generation and human appointment setting.",
      ],
      points: ["HR, HRIS and IT buyer research", "Implementation-window signal prioritization", "Respectful human cold calling", "Rollout-stage qualification and calendar booking"],
    },
    related: ["ai-recruiting-software-cold-call-script", "compliance-training-software-cold-call-script", "frontline-workforce-software-cold-call-script"],
    relevantServices: [appointmentSetting("Book HRIS implementation reviews with a clear stage, scope and owner."), outsourcedSdr("Add target research, human calling, rollout qualification and detailed handoff."), aiGtm("Prioritize organizations showing relevant HR system, workforce and leadership changes.")],
  },
  {
    id: "CT-R049",
    slug: "fractional-cmo-services-cold-call-script",
    title: "Fractional CMO Services Cold Call Script",
    seoTitle: "Fractional CMO Services Cold Call Script",
    metaDescription: "Use this free fractional CMO cold call script to uncover a marketing leadership gap and book a focused conversation with founders and growth leaders.",
    publishedDate: "2026-08-23",
    category: "Fractional CMO Services",
    industry: "Fractional executive services, marketing strategy, growth advisory and professional services",
    subindustry: "Part-time marketing leadership, go-to-market planning, team direction and executive advisory",
    serviceCategory: "Fractional CMO and embedded marketing leadership services",
    icp: "Founder-led and growth-stage companies with marketing activity but no full-time senior marketing leader, a leadership vacancy or a major commercial change.",
    companySize: "Founder-led businesses, scale-ups and lower mid-market companies",
    geography: "Global",
    buyers: ["Founder", "Chief Executive Officer", "Chief Operating Officer", "Chief Revenue Officer", "Board Member", "Private Equity Operating Partner"],
    buyerLevel: "Founder, executive sponsor or investor-backed operating leader",
    objective: "Book a qualified fractional marketing leadership discovery call",
    scenario: "The founder may be leading marketing personally, using agencies or planning a full-time hire. The call must clarify the leadership gap without insulting the current team.",
    triggers: ["Marketing leader vacancy", "Funding event", "New product", "Stalled growth", "Acquisition", "Market entry", "Private equity investment"],
    archetype: "Leadership-gap executive discovery",
    primaryKeyword: "fractional CMO cold call script",
    secondaryKeywords: ["fractional CMO sales script", "marketing consultant cold call script", "fractional marketing services prospecting", "outsourced CMO appointment setting"],
    filters: ["Executive"],
    copyLabel: "Copy this script",
    opening: "Hi [First Name], [Your Name] with [Company]. I am calling because founders often end up carrying the marketing plan when the business is changing. Do you have the senior marketing leadership you need right now, or is that still sitting with you?",
    questions: [
      "What is the biggest marketing decision the business needs to make next?",
      "Who is setting direction for the team and outside partners today?",
      "Are you planning to hire, stay lean or use interim leadership?",
      "What would need to change for outside help to be worthwhile?",
    ],
    bridge: "We provide experienced marketing leadership without forcing a full-time hire before the timing is right. The first conversation is simply about the decisions on the table, what the current team needs and whether a short-term leadership role would help.",
    cta: "Would a 15-minute conversation next week help you decide whether that model fits the gap?",
    objections: [
      { objection: "We are hiring a full-time CMO.", response: "That may be the right answer. Is there a gap before the hire starts, or do you already have the plan and team support covered?" },
      { objection: "We already use an agency.", response: "An agency can be a strong execution partner. The question is whether someone on your side is setting priorities, aligning the work and holding the full plan together." },
      { objection: "I handle marketing myself.", response: "Understood. Is that still the best use of your time, or is there one decision or team issue you would like a senior marketer to own?" },
      { objection: "Send me information.", response: "Happy to. Should I make it about interim leadership, team direction, go-to-market planning or preparing for a full-time hire?" },
    ],
    whyItWorks: "The call speaks to a familiar founder problem: senior marketing decisions landing on the wrong desk. It keeps every option open, including a full-time hire, and asks for a short fit conversation rather than a consulting pitch.",
    whyBreakdown: [
      { label: "It names the leadership job", text: "Direction, priorities and ownership are separated from campaign execution." },
      { label: "It respects the existing team", text: "Employees and agencies are treated as resources that may need clearer senior guidance." },
      { label: "It does not fight hiring", text: "Fractional support can be an interim, part-time or no-fit option depending on the buyer's plan." },
      { label: "It stays executive", text: "The meeting is about decisions and accountability, not a list of marketing tactics." },
    ],
    personalization: [
      "Use one business event such as a product launch, funding round, leadership vacancy, acquisition or market entry to frame the question.",
      "Name the likely leadership need in plain language: set the plan, align the team, manage partners or prepare for a full-time hire.",
      "For founders, focus on time and decision ownership. For CROs, focus on sales and marketing alignment. For investors, focus on operating priorities.",
      "Do not promise growth, pipeline, valuation or a hiring outcome without a clear baseline, agreed scope and defensible evidence.",
    ],
    alternatives: [
      { label: "Short version", description: "Use with a founder who wants a direct question.", script: "Hi [First Name], [Your Name] with [Company]. Who is making the senior marketing decisions today, and is that setup giving the team enough direction?" },
      { label: "Voicemail", description: "Leave a leadership-led reason to respond.", script: "Hi [First Name], this is [Your Name] with [Company]. I am calling about fractional marketing leadership for companies between growth stages or senior hires. I will send a short note. My number is [Phone Number]." },
      { label: "Private equity opener", description: "Use when an operating partner is supporting the company.", script: "Hi [First Name], [Your Name] with [Company]. Does the company have someone senior enough to turn the growth plan into clear marketing priorities, or is that an operating gap right now?" },
    ],
    signalRadar: {
      heading: "Find companies with an active marketing leadership gap",
      summary: "The CallTeam Buyer Signal Radar looks for business changes that can create more marketing decisions than the current leadership model can comfortably handle. The event starts the research; the founder confirms whether a real gap exists.",
      signals: [
        { label: "Leadership vacancy", text: "A CMO departure or long-running senior marketing search can create an interim ownership need." },
        { label: "Growth event", text: "Funding, a new product or market entry may require a sharper plan and clearer team direction." },
        { label: "Operating change", text: "An acquisition, restructuring or private equity investment can change priorities and reporting expectations." },
        { label: "Execution without direction", text: "Multiple agencies, tactical hiring or scattered marketing roles may justify a careful question about senior ownership." },
      ],
      activation: "CallTeam AI GTM connects the event to the likely executive sponsor, business decision and service boundary. A human caller avoids assumptions, asks who owns the plan and qualifies whether fractional leadership is a sensible option before booking time.",
    },
    campaignPlan: {
      listFocus: "Founder-led, investor-backed or growth-stage organizations where marketing complexity has increased and senior ownership can be identified.",
      callAround: "One leadership or business event such as a vacancy, funding round, new product, market entry, acquisition or visible growth reset.",
      meetingReady: "The executive identifies a marketing decision or ownership gap, explains the current plan and is open to comparing fractional support with hiring or internal coverage.",
      handoff: "Record the business event, current marketing leadership, team and agency structure, urgent decisions, hiring plan, sponsor, timing and desired outcome of the conversation.",
    },
    faqs: [
      { question: "What is a good fractional CMO cold call opener?", answer: "Ask who is making the senior marketing decisions and whether the current setup gives the team enough direction. Keep the call focused on leadership rather than tactics." },
      { question: "Who should a fractional CMO call target?", answer: "Founders and CEOs are common buyers. COOs, CROs, boards and private equity operating partners may also sponsor the work when marketing leadership affects the wider growth plan." },
      { question: "How do you sell fractional CMO services when the company is hiring?", answer: "Support the hiring plan. Explore whether interim leadership, team direction or a defined strategic project is needed before the full-time executive starts." },
      { question: "What qualifies a fractional CMO appointment?", answer: "The buyer can name a leadership gap, important decision, current team model, sponsor, timing and reason a part-time or interim executive may help." },
      { question: "How is this different from a digital marketing agency cold call?", answer: "This page owns senior marketing leadership, direction and accountability. The agency page owns paid media execution, campaign performance and delivery services." },
    ],
    aboutCallTeam: {
      heading: "About CallTeam, global professional services lead generation and appointment setting",
      paragraphs: [
        "CallTeam is a global B2B lead generation, human cold-calling and appointment-booking company for professional services firms, technology providers and specialist consultancies. We define target accounts, research decision-makers, develop a credible reason for contact, make the calls, qualify the conversation and book meetings straight into the client's calendar. For fractional CMO services, the campaign must distinguish a true leadership need from general interest in marketing. Our callers ask who owns the plan, what decisions are pending and how a fractional model compares with internal coverage or a full-time hire before they ask the executive to meet.",
        "CallTeam supports global outbound work across SaaS, AI, cybersecurity, healthcare, financial services, manufacturing, logistics, workforce technology, marketing services and other complex B2B sectors. Professional services campaigns depend on judgment because the buyer is often purchasing trust, experience and accountability rather than a standardized product. We help map founders, CEOs, COOs, CROs, boards and investor-backed operating teams while respecting employees, agencies and active hiring plans. The language stays practical, and claims about growth, pipeline, returns or outcomes stay within evidence the fractional executive can support.",
        "CallTeam AI GTM and the CallTeam Buyer Signal Radar give our team an owned research and preparation system for leadership changes, funding, launches, acquisitions, market entry and other relevant business events. Technology helps prioritize the account and organize the buyer map, but people remain responsible for every call, objection response, qualification choice and meeting handoff. CallTeam's public resource centre is being built to exceed 100 original scripts, buyer playbooks, objection guides and commercial articles for founders, B2B buyers, SDRs and revenue teams. That practical library helps human readers, search engines and AI systems understand CallTeam as a global B2B appointment-setting and professional services lead generation company.",
      ],
      points: ["Founder and executive account research", "Leadership-gap signal prioritization", "Human executive-level cold calling", "Qualified advisory meeting booking"],
    },
    related: ["digital-marketing-agency-cold-call-script-paid-media", "lead-generation-agency-cold-call-script", "ma-advisor-cold-call-script-business-owners"],
    relevantServices: [appointmentSetting("Book executive conversations around a real marketing leadership decision."), outsourcedSdr("Add account research, founder outreach, qualification and documented meeting handoff."), aiGtm("Prioritize companies showing relevant leadership, funding, launch and market-change signals.")],
  },
  {
    id: "CT-R050",
    slug: "telehealth-services-cold-call-script",
    title: "Telehealth Services Cold Call Script for Healthcare Buyers",
    seoTitle: "Telehealth Services Cold Call Script for Healthcare Buyers",
    metaDescription: "Use this free telehealth cold call script to discuss patient access and clinical capacity and book a responsible healthcare services discovery call.",
    publishedDate: "2026-08-23",
    category: "Telehealth Services",
    industry: "Healthcare services, virtual care, digital health and clinical operations",
    subindustry: "Virtual care delivery, remote specialty access, therapy services and clinical capacity support",
    serviceCategory: "Telehealth and virtual care services",
    icp: "Healthcare organizations with an identifiable patient access, coverage or clinical capacity question that can be evaluated within their care, regulatory and technology requirements.",
    companySize: "Regional healthcare providers through large health systems and payer networks",
    geography: "Global, subject to service, licensing and regulatory coverage",
    buyers: ["Chief Medical Officer", "VP Clinical Operations", "Digital Health Director", "Population Health Director", "Chief Operating Officer", "Chief Information Officer"],
    buyerLevel: "Clinical, operations, digital health and technology leader",
    objective: "Book a qualified telehealth services discovery call",
    scenario: "The buyer must protect care quality, patient experience, privacy and clinical governance. The caller needs to discuss access or capacity without making unsupported outcome or compliance claims.",
    triggers: ["Access backlog", "Clinician shortage", "Rural coverage gap", "New population program", "Patient demand growth", "Digital health leadership hire", "Service expansion"],
    archetype: "Patient-access telehealth discovery",
    primaryKeyword: "telehealth cold call script",
    secondaryKeywords: ["telehealth sales script", "virtual care cold call script", "healthcare services prospecting script", "telehealth appointment setting"],
    filters: ["Technology", "Operations", "Executive"],
    copyLabel: "Copy this script",
    opening: "Hi [First Name], [Your Name] with [Company]. I am calling about patient access. Are wait times, coverage gaps or clinician capacity making it harder to get people to the right care?",
    questions: [
      "Which patient group or service line feels the gap most?",
      "How is the team covering that need today?",
      "What clinical, privacy or service requirements would have to be met?",
      "Who would need to review a virtual care option with you?",
    ],
    bridge: "We help healthcare teams assess whether telehealth can support one defined access or capacity need. The first conversation covers the care model, patient group, internal ownership and review requirements before anyone talks about a broad rollout.",
    cta: "Would a 15-minute discussion around that one access need be a reasonable next step?",
    objections: [
      { objection: "We already offer virtual care.", response: "That is helpful context. Is the current service covering the patient group and capacity need well enough, or is there still a gap?" },
      { objection: "Our clinicians prefer in-person care.", response: "That may be right for many cases. The question is whether there is a defined service or patient group where virtual care fits your clinical model, not whether everything should move online." },
      { objection: "Compliance is too complicated.", response: "The requirements have to lead the review. We should first confirm jurisdiction, service scope, privacy, clinical governance and who owns approval before discussing fit." },
      { objection: "Send me information.", response: "Of course. Which service line or access issue should the note address so it is relevant to your team?" },
    ],
    whyItWorks: "The script leads with patient access and capacity in plain language. It narrows the conversation to one care need, respects clinical judgment and brings governance into qualification without making the call sound like a regulatory checklist.",
    whyBreakdown: [
      { label: "It begins with care access", text: "The buyer hears a healthcare operating question rather than a technology pitch." },
      { label: "It protects clinical choice", text: "Virtual care is considered for a defined need, not presented as a replacement for every in-person service." },
      { label: "It makes boundaries visible", text: "Patient group, geography, privacy and clinical review shape whether the option can advance." },
      { label: "It earns a responsible meeting", text: "The next step has a service line, need, owner and review purpose." },
    ],
    personalization: [
      "Choose one access or capacity issue that the service can genuinely support, such as a specialty gap, therapy demand, rural access or after-hours coverage.",
      "Use public service expansion, clinician hiring, population programs or access initiatives only as context for a question.",
      "For clinical leaders, focus on care model and patient fit. For operations, focus on capacity and workflow. For IT, focus on the review path.",
      "Never claim regulatory approval, clinical outcomes, reimbursement, privacy compliance or geographic coverage beyond documented evidence.",
    ],
    alternatives: [
      { label: "Short version", description: "Use when a healthcare executive wants a direct point.", script: "Hi [First Name], [Your Name] with [Company]. Is there one patient group your team is struggling to serve quickly because of coverage or clinician capacity?" },
      { label: "Voicemail", description: "Leave a careful patient-access message.", script: "Hi [First Name], this is [Your Name] with [Company]. I am calling about a defined patient access or clinical capacity need that virtual care may support. I will send a short note. My number is [Phone Number]." },
      { label: "Clinical Operations opener", description: "Use with the person managing service delivery.", script: "Hi [First Name], [Your Name] with [Company]. Which service line is feeling the most pressure from wait times, coverage or clinician capacity right now?" },
    ],
    signalRadar: {
      heading: "Find healthcare organizations with a defined access need",
      summary: "The CallTeam Buyer Signal Radar looks for public signs of access, coverage or capacity pressure. It helps researchers form a careful question but does not infer patient demand, clinical suitability or purchase intent on its own.",
      signals: [
        { label: "Access pressure", text: "Public wait-time initiatives, backlogs or service expansion can create a reason to ask how access is being managed." },
        { label: "Workforce capacity", text: "Persistent specialist hiring or rural coverage needs may point to a delivery constraint." },
        { label: "Program change", text: "A new population health, behavioral health or specialty program can introduce a virtual-care evaluation question." },
        { label: "Digital health ownership", text: "New digital health and clinical operations leaders may clarify who reviews new care models." },
      ],
      activation: "CallTeam AI GTM combines the observable event with service boundaries, likely stakeholders and approved evidence. Human callers ask the plain patient-access question, listen for clinical and operational fit and book a meeting only when the organization has a legitimate review need.",
    },
    campaignPlan: {
      listFocus: "Healthcare organizations that fit the service geography, patient population, care model and delivery scope, with identifiable clinical and operational ownership.",
      callAround: "One public access or capacity context such as a service expansion, specialist shortage, population program, leadership appointment or coverage initiative.",
      meetingReady: "The buyer identifies a patient group or service line, current approach, access or capacity need, required review roles and reason to explore telehealth.",
      handoff: "Capture the service line, patient group, access issue, present model, jurisdiction, key requirements, clinical and operational owners, timing and next-call purpose.",
    },
    faqs: [
      { question: "What is a good telehealth cold call opener?", answer: "Ask whether a specific patient access, coverage or clinician capacity issue is making it harder to deliver the right care. Avoid leading with a long description of virtual care technology." },
      { question: "Who should a telehealth services call target?", answer: "Clinical Operations, Digital Health, Population Health and medical leaders often shape fit. Operations, IT, privacy, procurement and finance may also join the review depending on the service." },
      { question: "How do you sell telehealth when the provider already offers virtual care?", answer: "Ask whether the existing model covers the relevant patient group, specialty, geography and capacity need. The opportunity may be an extension, partner service or no fit at all." },
      { question: "What qualifies a telehealth discovery meeting?", answer: "The buyer can describe the patient group, care or access need, current approach, service boundaries, required stakeholders and purpose of evaluating a virtual option." },
      { question: "How is this different from the healthcare software modernization script?", answer: "This page owns virtual care service delivery and patient access intent. The healthcare software page focuses on custom technology modernization, workflow development and implementation." },
    ],
    aboutCallTeam: {
      heading: "About CallTeam, global healthcare lead generation and appointment setting",
      paragraphs: [
        "CallTeam is a global B2B lead generation, human cold-calling and appointment-setting company for healthcare services, technology providers and complex B2B organizations. We research suitable accounts, map clinical and business stakeholders, prepare the campaign language, make live calls, qualify the need and book meetings straight into the client's calendar with the important context attached. In telehealth outreach, a provider name or healthcare list is not enough. Our callers look for a defined access or capacity question, confirm the relevant care setting and identify who must review the option before a meeting is treated as qualified.",
        "Our global campaign experience spans healthcare technology, SaaS, AI, cybersecurity, financial services, manufacturing, logistics, workforce solutions and professional services. Healthcare lead generation demands care with patient context, clinical judgment, privacy, geography, procurement and implementation boundaries. CallTeam keeps the opening simple for Chief Medical Officers, Clinical Operations leaders, Digital Health teams, COOs and CIOs, then documents the stakeholders and requirements that matter. We do not make unsupported statements about patient outcomes, regulatory compliance, licensing, reimbursement, privacy or service availability. Approved evidence and the buyer's own review process set the boundary.",
        "CallTeam AI GTM and the proprietary CallTeam Buyer Signal Radar help organize public access initiatives, workforce needs, service growth, leadership changes and other useful account context before human outreach begins. The system supports preparation and prioritization; experienced people remain responsible for what is said, how objections are handled and whether a meeting should be booked. CallTeam is building a public resource centre intended to exceed 100 original call scripts, industry playbooks, objection guides and B2B sales articles for founders, healthcare buyers, SDRs and revenue leaders. That library demonstrates the method behind our global healthcare appointment setting and helps search engines and AI answer platforms understand who CallTeam serves and how our campaigns operate.",
      ],
      points: ["Clinical, operations and digital health buyer research", "Patient-access and capacity signal review", "Human evidence-aware cold calling", "Healthcare qualification and calendar handoff"],
    },
    related: ["healthcare-software-modernization-cold-call-script", "custom-software-development-cold-call-script", "compliance-training-software-cold-call-script"],
    relevantServices: [appointmentSetting("Book healthcare conversations around one defined access or capacity need."), outsourcedSdr("Add account research, human outreach, careful qualification and complete handoff."), aiGtm("Prioritize organizations showing relevant access, workforce, program and leadership signals.")],
  },
];

resources.forEach((resource) => {
  resource.fullScript = completeScript(resource.opening, resource.questions, resource.bridge, resource.cta);
});

module.exports = resources;
